<?php
namespace Apparto\BonobosBundle\Entity;
use Doctrine\ORM\EntityRepository;
use Apparto\BonobosBundle\Entity\User;
/**
 * CarteFidelite
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function modify($id,$age,$famille,$race,$nouriture)
    {
   $query=$this->getEntityManager()->createQuery("Update BonobosBundle:User u SET u.age=:age,u.race=:race,u.famille=:famille,u.nouriture=:nouriture where u.id=:id ");
      $query->setParameter('id',$id);
      $query->setParameter('age',$age);
      $query->setParameter('race',$race);
      $query->setParameter('nouriture',$nouriture);
      $query->setParameter('famille',$famille);

         $query->execute();
    }
 
    
 
     
}